# Generated by Django 4.0.6 on 2022-08-02 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_about_description_remove_about_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='social_media',
        ),
    ]
