# Generated by Django 4.0.6 on 2022-07-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_category_zonecat_delete_tag_article_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='zonecat',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
