# Generated by Django 4.0.5 on 2022-07-30 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
