# Generated by Django 4.1.1 on 2022-09-08 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='massage',
            new_name='message',
        ),
    ]
